{% set name = "jupyterlab-pullrequests" %}
{% set version = "3.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pullrequests-{{ version }}.tar.gz
  sha256: 45515c46203525706579656c318fa416946731578d6489173dc1ed082a02b558

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jupyterlab >=3.0,<4
    - jupyterlab-git >=0.30.0,<0.40.0a0
    - python >=3.6

test:
  imports:
    - jupyterlab_pullrequests
    - jupyterlab_pullrequests.managers
  commands:
    - pip check
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_pullrequests.*OK"  # [unix]
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/pullrequests.*OK"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/pull-requests
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Manage Pull Requests in JupyterLab
  description: A JupyterLab extension for reviewing pull requests.

extra:
  recipe-maintainers:
    - fcollonval
    - bollwyvl
